# Proyecto final ASXI 2016-2017

#### Autor: Altair 
#### Fecha: 04/2017-

version: '2'

services:

    ## Servidor FREERADIUS
    radius: # Definir contenedor
      container_name: server_radius
      build:
        context: radius_server
      ports: # Mapeo de puertos
        - "1812:1812"
        - "1813:1813"
      networks:
        - new-network
      links:
        - mysql
        - ldap
        - kerberos

    ## Servidor MYSQL
    mysql:
      container_name: server_mysql
      build:
        context: mysql_server
      ports:
        - "3306:3306"

    ## Servidor LDAP
    ldap:
      container_name: server_ldap
      build:
        context: ldap_server
      ports:
        - "389:389"
        - "636:636"
     links:
       - kerberos

    ## Servidor KERBEROS
    kerberos:
      container_name: server_kerberos
      build:
        context: kerberos_server
      ports:
        - "464:464"
        - "749:749"

    ## Servidor WEB
    http:
      container_name: server_http
      build:
        context: http_server
      ports:
        - "80:80"
        - "443:443"

      links:
        mysql
    
    ## Autoridad certificadora
    ca:
      container_name: autoridad_certificadora
      build:
        context: ca_host
    

networks:
  new-network:
    driver: bridge
