version: '2'

services:

    radius: # Definir contenedor
      container_name: server_radius
      build:
        context: radius_server
      ports: # Mapeo de puertos
        - "1812:1812"
        - "1813:1813"
      networks:
        - new-network
      links:
        - mysql
        - ldap
        - kerberos
    
    mysql:
      container_name: server_mysql
      build:
        context: mysql_server
      ports:
        - "3306:3306"

    ldap:
      container_name: server_ldap
      build:
        context: ldap_server
      ports:
        - "389:389"
        - "636:636"

    kerberos:
      container_name: server_kerberos
      build:
        context: kerberos_server
      ports:
        - "464:464"
        - "749:749"

    http:
      container_name: server_http
      build:
        context: http_server
      ports:
        - "80:80"
        - "443:443"

    ca:
      container_name: autoridad_certificadora
      build:
        context: ca_host
    

networks:
  new-network:
    driver: bridge
