
#######
#######
# Proyecto final ASXI 2016-2017
# Autor: Altair 
# Fecha: 04/2017 
# Archivo: docker-compose.yml
#######
#######

##  Modificaciones
# 
#
#
##

# Versión que utiliza docker-compose
version: '2'

## Servicios que componen este Docker-Compose
services:

    freeradius: #Nombre del servicio
      container_name: server_radius  # Nombre del contenedor y hostname
      build: # Especifica el directorio que contenga el Dockerfile
        context: ./radius_server # ! nombre Dockerfile  ex: Dockerfile.alternate nombre no estandar
        dockerfile: Dockerfile.radius
      ports:
       - 1812:1812
       - 1813:1813

    mysql:
      container_name: server_mysql
      build:
        context: ./mysql_server
        dockerfile: Dockerfile.mysql

