FROM resin/rpi-raspbian

MAINTAINER "Altair version 0.1 LDAP"

### CONF FILES

RUN mkdir /opt/docker
COPY conf_files /opt/docker

RUN \
 apt-get update && \
 apt-get install vim \
 apt-get install -y -qq slapd ldap-utils && \
 rm -rf /var/lib/apt/lists/*
;exit 0 

RUN service slapd start ; \
 cd /opt/docker/conf_files && \
 ldapadd -Y EXTERNAL -H ldapi:/// -f back.ldif && \
 ldapadd -x -D cn=admin,dc=zion,dc=com -w ZAaAJ1989-2017 -c -f front.ldif && \
 ldapadd -x -D cn=admin,dc=zion,dc=com -w ZAaAJ1989-2017 -c -f users.ldif ; exit 0

EXPOSE 389
CMD slapd -h 'ldap:/// ldapi:///' -g openldap -u openldap -F /etc/ldap/slapd.d -d stats
ENTRYPOINT ["/bin/bash"]
